name: data-prog-env
channels:
  - defaults
dependencies:
  - scikit-learn
  - pandas=2.3.3
  - seaborn=0.13.2
  - ipykernel=6.31.0
  - networkx=3.5
  - python=3.13.9
  - numpy=2.3.5
  - scikit-image=0.25.2
  - matplotlib=3.10.6
  - requests=2.32.5
  - flake8=7.3.0
prefix: /home/armend/miniconda3/envs/data-prog-env
